# SPDX-License-Identifier: GPL-2.0-only
# Build sunxi-g2d.ko module from multiple object files
sunxi-g2d-y := sunxi-g2d-main.o \
               sunxi-g2d-rcq.o

obj-$(CONFIG_DRM_SUN8I_G2D) += sunxi-g2d.o
